### ISSUE TITLE
Tooltip disappears on second render in Safari

### ISSUE THREAD

**Issue by alexflorisca** [Financial-Times/o-tooltip#23]
Test on browserstack in Safari 8 on Yosemite. Using the click demo as an example, when the tooltip is clicked first time, it displays properly. It also closes properly. If I then click the button again, the tooltip animation runs but the tooltip disappears after the animation finishes.

**Comment by alicebartlett** [comment]
Looking at this now. I can replicate it in chrome too. Thank you for reporting.
