### ISSUE TITLE
Tooltip hidden by overflow property of parent

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-tooltip#28]
When a tooltip's target is inside an element with `overflow: hidden`, the tooltip itself can sometimes be hidden by the parent overflow. Pseudo-code example:

```
<div style="overflow: hidden;">
    <target>example</target>
    <tooltip position="bottom">example</tooltip>
</div>
```

In the example above, the tooltip is clipped by the outer div, because it only expands to the height of its non-positioned children.

There's not really a way around this, as the tooltip position calculation assumes that the tooltip and target share a parent. Discussed this with @notlee and @jkerr321, it's not possible in this particular case to remove the overflow from the parent element.

**Comment by gvonkoss** [comment]
This has been fixed with the latest release (v3).
