### ISSUE TITLE
No font family set for tooltip content

### ISSUE THREAD

**Issue by jonnywyatt** [Financial-Times/o-tooltip#47]
Is the aim / philosophy for Origami components to not specify font family (with a dependency on o-typography)?
Otherwise, I'd like to raise a PR to set the font family with the oTypographySans(0) mixin.

**Comment by notlee** [comment]
As discussed in Slack:

We don't seem to have a hard rule. Some components use `o-typography` to set their font and others do not. It's usually better in my opinion to avoid being prescriptive where possible. This case could be argued either way. As other Origami components set their typography and as we have [a precedent](https://github.com/Financial-Times/next-myft-page/blob/02f86559338e65976ba40f42559c2a47bf134a67/client/components/tooltip/main.scss#L10) in another ft repo, where duplication can be avoided and consistency maintained, I think your suggestion is a good one. 👍 

Aside: We're working on a mechanism to deliver components with less ft.com specific boilerplate to avoid the need to override styles like this as much in the future.

**Comment by JakeChampion** [comment]
Feel free to open a PR with the change @jonnywyatt, if you don't have capacity let us know and we can schedule the work ourselves.

**Comment by chee** [comment]
looks like we did this? :) https://github.com/Financial-Times/o-tooltip/blob/master/src/scss/_mixins.scss#L63
