### ISSUE TITLE
To address a display issue with o-tooltips when used on a nav element. 

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-tooltip#55]
This was happening when reloading at just under 1440px wide. At smaller breakpoints the right align tooltip kicks in and solves this issue 

![pasted image at 2018_04_10 10_50 am](https://user-images.githubusercontent.com/11214093/38555275-7a5de040-3cbd-11e8-9cea-b303bb031564.png)

**Comment by dan-searle** [comment]
I'm seeing a very similar issue.

With `position` set to `below`, at the largest breakpoint the right hand side of the tooltip is going offscreen:

<img width="230" alt="screen shot 2018-04-17 at 15 50 58" src="https://user-images.githubusercontent.com/2759279/38877777-5b1e7696-4257-11e8-96e3-c218fb4bdecc.png">

At the next (smaller) breakpoint, the tooltip then changes from middle-aligned to left aligned, making the problem worse:
<img width="237" alt="screen shot 2018-04-17 at 15 51 13" src="https://user-images.githubusercontent.com/2759279/38877783-5cd54334-4257-11e8-8943-c97ea05ae652.png">

With `position` set to anything but `below`, the tooltip positions itself to the right:
<img width="200" alt="screen shot 2018-04-17 at 15 57 44" src="https://user-images.githubusercontent.com/2759279/38878108-1dd9ce4c-4258-11e8-9a06-ddee74620a8a.png">

**Comment by notlee** [comment]
This should be solved in v3.1.2 https://github.com/Financial-Times/o-tooltip/releases/tag/3.1.2
