### ISSUE TITLE
Allow tooltip position to be offset

### ISSUE THREAD

**Issue by jonnywyatt** [Financial-Times/o-tooltip#56]
Possibly, add support for a new option which could allow the tooltip position to be nudged in relation to the target.
eg 
```
offset: {
    top: -5px,
    left: 10px
}
```
Example:
To move the tooltip slightly downwards
![image](https://user-images.githubusercontent.com/471250/38622465-266d06ee-3d9b-11e8-9a7a-090043d6f678.png)

**Comment by chee** [comment]
this feature seems like it could lead to more fragile code, and there may be better ways to solve this issue within the app.

please feel free to create a new issue if this is a problem in the future.
